DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
    cat_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id integer NOT NULL,
    cat_name CHAR(24) NULL DEFAULT NULL,
    cat_position smallint  NULL DEFAULT NULL,
    icon TEXT NULL DEFAULT NULL,
    keywords text NULL DEFAULT NULL,
    active boolean NULL DEFAULT true,
    cat_description CHAR(128) NULL DEFAULT NULL
);

INSERT INTO categories (parent_id, cat_name, cat_description) VALUES
( 0, 'Раздел 1',  'Раздел 1'),
( 0, 'Раздел 2', 'Раздел 1'),
( 0, 'Раздел 3', 'Раздел 1'),
( 1, 'Раздел 1.1', 'Раздел 1'),
( 1, 'Раздел 1.2',  'Раздел 1'),
( 4, 'Раздел 1.1.1',  'Раздел 1'),
( 2, 'Раздел 2.1',  'Раздел 1'),
( 2, 'Раздел 2.2',  'Раздел 1'),
( 3, 'Раздел 3.1',  'Раздел 1');

update categories set parent_id = 1 where parent_id =0
select * from categories



DROP TABLE IF EXISTS data_visits;
CREATE TABLE data_visits (
    data_id integer NOT NULL,
    user_hash CHAR(32) NULL DEFAULT NULL,
);



DROP TABLE IF EXISTS data_relationship;
CREATE TABLE data_relationship (
    data_id integer NOT NULL,
    cat_id integer NOT NULL
);


DROP TABLE IF EXISTS catalog_data;
CREATE TABLE catalog_bata(
   data_id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url CHAR(24) NULL DEFAULT NULL,
title CHAR(48 ) NULL DEFAULT NULL,
  ico TEXT NULL DEFAULT NULL,
  add_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  modify_date TIMESTAMP NULL DEFAULT NULL,
  description_short VARCHAR(255) NULL DEFAULT NULL,
  description_full TEXT  NULL DEFAULT NULL,
visits INTEGER NULL DEFAULT 0,
  active boolean NULL DEFAULT true,
   mark VARCHAR(255) NULL DEFAULT NULL
);

INSERT INTO catalog_data(url,title,ico,description_short,description_full,mark) VALUES
('ya.ru','Яндекс — поисковый интернет-портал','asdasdasd','Поисковая машина и почта. Поиск страниц, новостей, товаров, картинок. Расширенный поиск, поиск по регионам.','«Яндекс» — российская транснациональная компания, зарегистрированная в Нидерландах и владеющая одноимённой системой поиска в Сети, интернет-порталами и службами в нескольких странах. Наиболее заметное положение занимает на рынках России, Турции, Белоруссии и Казахстана.','test record');


select * from catalog_bata


